language: node_js
node_js:
  - '10'

dist: trusty
sudo: false
addons:
  chrome: stable

cache: npm

jobs:
  include:
    - stage: Greenkeeper
      before_install:
        - npm install -g npm@5
        - npm install -g greenkeeper-lockfile@1
      install: npm install
      before_script: greenkeeper-lockfile-update
      after_script: greenkeeper-lockfile-upload
    - stage: Audit
      before_script:
        - npm audit --json >> $TRAVIS_BUILD_DIR/audit/report.json || true
      script:
        - npm run audit:process
    - stage: Test
      script: npm test
    

notifications:
  email: false
